# Generated by Django 3.2.3 on 2021-06-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
