# Generated by Django 3.2.3 on 2021-06-08 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userflow', '0002_auto_20210608_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Phone',
            new_name='phone',
        ),
    ]
